package com.hartwig.actin.personalization.datamodel

enum class LabMeasure(val unit: Unit) {
    ALBUMINE(Unit.GRAM_PER_LITER),
    ALKALINE_PHOSPHATASE(Unit.UNIT_PER_LITER),
    CARCINOEMBRYONIC_ANTIGEN(Unit.MICROGRAM_PER_LITER),
    LACTATE_DEHYDROGENASE(Unit.UNIT_PER_LITER),
    LEUKOCYTES_ABSOLUTE(Unit.BILLIONS_PER_LITER),
    NEUTROPHILS_ABSOLUTE(Unit.BILLIONS_PER_LITER)
}