package com.hartwig.actin.personalization.datamodel

enum class MetastasesRadiotherapyType {
    PROPHYLACTIC_RADIOTHERAPY_TO_THE_CNS,
    RADIOTHERAPY_AIMED_AT_METASTASES_NNO,
    RADIOTHERAPY_FOR_LYMPH_NODE_METASTASES,
    RADIOTHERAPY_ON_BONE_METASTASES,
    RADIOTHERAPY_ON_BRAIN_METASTASES_NNO,
    RADIOTHERAPY_ON_BRAIN_METASTASES_STEREOTACTIC_GAMMA_KNIFE_CYBER_KNIFE,
    RADIOTHERAPY_ON_BRAIN_METASTASES_WHOLE_BRAIN,
    RADIOTHERAPY_ON_LEPTOMENINGEAL_METASTASES,
    RADIOTHERAPY_ON_LIVER_METASTASES,
    RADIOTHERAPY_ON_LUNG_METASTASES,
    RADIOTHERAPY_ON_PLEURAL_METASTASES,
    RADIOTHERAPY_ON_SKIN_METASTASES,
    THERAPY_AIMED_AT_METASTASES_THROUGH_RADIOISOTOPES,
    TRANSARTERIAL_RADIOEMBOLIZATION_FOR_LIVER_METASTASIS,
}