steps:
  - id: 'Maven build using cache'
    name: 'maven:3.9.7-eclipse-temurin-17'
    entrypoint: mvn
    args: [ 'test' ]

  - id: 'Python tests'
    name: 'python:3.11'
    entrypoint: bash
    env:
      - PYTHONPATH=prediction/src/main/python
    args:
      - -c
      - |
        pip install -r prediction/src/main/python/requirements.txt
        pip install pytest
        pytest prediction/src/test/python

options:
  machineType: 'E2_HIGHCPU_8'
