steps:
  - id: 'Set version for maven'
    name: 'eu.gcr.io/hmf-build/maven-cache'
    args: [ 'versions:set -DnewVersion=$TAG_NAME --batch-mode' ]

  - id: 'Maven build using cache'
    name: 'eu.gcr.io/hmf-build/maven-cache'
    args: [ '-T 1C deploy --batch-mode' ]

options:
  machineType: 'E2_HIGHCPU_8'
