steps:
  - id: 'Set version for maven'
    name: 'maven:3.9.7-eclipse-temurin-17'
    args: [ 'versions:set -DnewVersion=$TAG_NAME --batch-mode' ]

  - id: 'Maven build using cache'
    name: 'maven:3.9.7-eclipse-temurin-17'
    args: [ '-T 1C deploy --batch-mode' ]

  - id: 'Python tests'
    name: 'python:3.11'
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r src/main/python/requirements.txt
        pip install pytest
        pytest src/test/python

options:
  machineType: 'E2_HIGHCPU_8'
