steps:
  - id: 'Set version for maven'
    name: 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-build-agent:2.0.0'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=$TAG_NAME', '--batch-mode' ]
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/.m2/repository
        
  - id: 'Maven build, test and deploy'
    name: 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-build-agent:2.0.0'
    entrypoint: mvn
    args: [ '-T', '2', 'deploy', '--batch-mode' ]
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/.m2/repository
        
  - id: 'Python tests'
    name: 'python:3.11'
    entrypoint: bash
    env:
      - PYTHONPATH=prediction/src/main/python
    args:
      - -c
      - |
        pip install -r prediction/src/main/python/requirements.txt
        pip install pytest
        pytest prediction/src/test/python

  - id: 'Build and push prediction with tag'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    dir: 'prediction'
    args: [ 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-personalization-prediction', '$TAG_NAME', 'Dockerfile' ]

options:
  machineType: 'E2_HIGHCPU_8'
