steps:
  - id: 'Python tests'
    name: 'python:3.11'
    entrypoint: bash
    env:
      - PYTHONPATH=prediction/src/main/python
    args:
      - -c
      - |
        pip install -r prediction/src/main/python/requirements.txt
        pip install pytest
        pytest prediction/src/test/python

  - id: 'Build and push prediction with tag'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    dir: 'prediction'
    args: [ 'europe-west4-docker.pkg.dev/actin-build/build-registry-docker/actin-personalization-prediction', '$TAG_NAME', 'Dockerfile' ]

options:
  machineType: 'E2_HIGHCPU_8'
