package com.hartwig.actin.personalization.database.datamodel

import com.hartwig.actin.personalization.datamodel.ReferenceSource
import com.hartwig.actin.personalization.datamodel.Sex
import com.hartwig.actin.personalization.datamodel.diagnosis.AnorectalVergeDistanceCategory
import com.hartwig.actin.personalization.datamodel.diagnosis.BasisOfDiagnosis
import com.hartwig.actin.personalization.datamodel.diagnosis.Sidedness
import com.hartwig.actin.personalization.datamodel.diagnosis.TumorLocation
import com.hartwig.actin.personalization.datamodel.diagnosis.TumorType

data class ReferenceEntry(
    val source: ReferenceSource,
    val sourceId: Int,
    val diagnosisYear: Int,
    val ageAtDiagnosis: Int,
    val isAlive: Boolean,
    val sex: Sex,
    val basisOfDiagnosis: BasisOfDiagnosis,
    val numberOfPriorTumors: Int,
    val hasDoublePrimaryTumor: Boolean,
    val primaryTumorType: TumorType,
    val primaryTumorLocation: TumorLocation,
    val sidedness: Sidedness?,
    val anorectalVergeDistanceCategory: AnorectalVergeDistanceCategory?,
    val mesorectalFasciaIsClear: Boolean?,
    val distanceToMesorectalFasciaMm: Double,
    val differentiationGrade: String,
    val clinicalTnmT: String,
    val clinicalTnmN: String,
    val clinicalTnmM: String,
    val pathologicalTnmT: String,
    val pathologicalTnmN: String,
    val pathologicalTnmM: String,
    val clinicalTumorStage: String,
    val pathologicalTumorStage: String,
    val investigatedLymphNodesCountPrimaryDiagnosis: Double,
    val positiveLymphNodesCountPrimaryDiagnosis: Double,
    val presentedWithIleus: Double,
    val presentedWithPerforation: Double,
    val venousInvasionDescription: String,
    val lymphaticInvasionCategory: String,
    val extraMuralInvasionCategory: String,
    val tumorRegression: String,
    val isMetachronous: Int,
    val numberOfLiverMetastases: String,
    val maximumSizeOfLiverMetastasisMm: Double,
    val investigatedLymphNodesCountMetastaticDiagnosis: Double,
    val positiveLymphNodesCountMetastaticDiagnosis: Double,
    val metastasisLocationGroups: String,
    val metastasisLocationGroupsDays: String,
    val earliestDistantMetastasisDetectionDays: Double,
    val AllWhoAssessments: String,
    val WhoAssessmentsDates: String,
    val WhoAssessmentBeforeMetastasisTreatment: Double,
    val WhoAssessmentDateBeforeMetastasisTreatment: Double,
    val WhoAssessmentAtMetastasisDetection: Double,
    val WhoAssessmentDateAtMetastasisDetection: Double,
    val AllAsaAssessments: String,
    val AsaAssessmentsDates: String,
    val AsaAssessmentBeforeMetastasisTreatment: String,
    val AsaAssessmentDateBeforeMetastasisTreatment: Double,
    val AsaAssessmentAtMetastasisDetection: String,
    val AsaAssessmentDateAtMetastasisDetection: Double,
    val lactateDehydrogenaseMetastasisDetection: Double,
    val alkalinePhosphataseMetastasisDetection: Double,
    val leukocytesAbsoluteMetastasisDetection: Double,
    val carcinoembryonicAntigenMetastasisDetection: Double,
    val albumineMetastasisDetection: Double,
    val neutrophilsAbsoluteMetastasisDetection: Double,
    val closestLabValueDateMetastasisDetection: Double,
    val surgeriesPrimary: String,
    val surgeriesPrimaryDates: String,
    val surgeriesMetastatic: String,
    val surgeriesMetastaticDates: String,
    val surgeriesGastroenterology: String,
    val surgeriesGastroenterologyDates: String,
    val hadHipec: Int,
    val hadHipecDate: Double,
    val radiotherapiesPrimary: String,
    val radiotherapiesPrimaryDates: String,
    val radiotherapiesMetastatic: String,
    val radiotherapiesMetastaticDates: String,
    val treatment: String,
    val firstTreatmentStartAfterMetastasis: Double,
    val treatmentStop: Double,
    val numberOfCycles: Double,
    val hasHadPriorSystemicTherapy: Int,
    val hadSurvivalEvent: Int,
    val hasHadPriorTumor: Int,
    val observedOsFromTumorIncidenceDays: Int,
    val observedOsFromMetastasisDetectionDays: Double,
    val observedOsFromTreatmentStartDays: Double,
    val systemicTreatmentPlanDuration: Double
)
