package com.hartwig.actin.personalization.ncr.interpretation.mapper

import com.hartwig.actin.personalization.datamodel.Location

object NcrLocationMapper {
    fun resolveLocation(code: String): Location {
        return when (code) {
            "C000" -> Location.UPPER_LIP_LIP_RED
            "C001" -> Location.LOWER_LIP_LIP_RED
            "C019" -> Location.TONGUE_BASE
            "C021" -> Location.TONGUE_TIP_AND_SIDE_EDGE
            "C022" -> Location.TONGUE_VENTRAL_SURFACE
            "C024" -> Location.TONSILLA_LINGUALIS
            "C031" -> Location.GUMS_LOWER_JAW
            "C040" -> Location.FLOOR_OF_MOUTH_ANTERIOR_PART
            "C041" -> Location.FLOOR_OF_MOUTH_LATERAL_PART
            "C050" -> Location.HARD_PALATE
            "C051" -> Location.SOFT_PALATE
            "C052" -> Location.UVULA
            "C060" -> Location.CHEEK_MUCOSA
            "C062" -> Location.RETROMOLAR_AREA
            "C079" -> Location.GLANDULA_PAROTID
            "C080" -> Location.GLANDULA_SUBMANDIBULARIS
            "C090" -> Location.TONSILNIS
            "C091" -> Location.TONSIL_FOLDS
            "C099" -> Location.TONSILS
            "C100" -> Location.VALLECULA
            "C103" -> Location.POSTERIOR_OROPHARYNGEAL_WALL
            "C111" -> Location.NASOPHARYNX_POSTERIOR_WALL
            "C119" -> Location.NASOPHARYNX_NOS
            "C129" -> Location.SINUS_PYRIFORM
            "C130" -> Location.POSTCRICOID_REGION
            "C131" -> Location.ARYEPIGLOTTIC_FOLD
            "C139" -> Location.HYPOPHARYNX_NOS
            "C148" -> Location.LIP_ORAL_CAVITY_PHARYNX_OVERLAPPING
            "C153" -> Location.ESOPHAGUS_UPPER_THIRD
            "C154" -> Location.ESOPHAGUS_MIDDLE_THIRD
            "C155" -> Location.ESOPHAGUS_LOWER_THIRD
            "C159" -> Location.ESOPHAGUS_NOS
            "C160" -> Location.GASTRIC_CARDIA
            "C161" -> Location.GASTRIC_FUNDUS
            "C162" -> Location.GASTRIC_CORPUS
            "C163" -> Location.GASTRIC_ANTRUM_PYLORI
            "C165" -> Location.GASTRIC_SMALL_CURVATURE_NOS
            "C166" -> Location.GASTRIC_GREATER_CURVATURE_NOS
            "C167" -> Location.GASTROESOPHAGEAL_JUNCTION
            "C168" -> Location.STOMACH_OVERHANG
            "C169" -> Location.STOMACH_NOS
            "C170" -> Location.DUODENUM
            "C171" -> Location.JEJUNUM
            "C172" -> Location.ILEUM
            "C178" -> Location.SMALL_INTESTINE_OVERLAPPING
            "C179" -> Location.SMALL_INTESTINE_NOS
            "C180" -> Location.COECUM
            "C181" -> Location.APPENDIX
            "C182" -> Location.ASCENDING_COLON
            "C183" -> Location.FLEXURA_HEPATICA
            "C184" -> Location.TRANSVERSE_COLON
            "C185" -> Location.FLEXURA_LIENALIS
            "C186" -> Location.DESCENDING_COLON
            "C187" -> Location.SIGMOID_COLON
            "C188" -> Location.COLON_OVERLAPPING
            "C189" -> Location.COLON_NOS
            "C199" -> Location.RECTOSIGMOID
            "C209" -> Location.RECTUM
            "C210" -> Location.ANUS_NOS
            "C211" -> Location.ANAL_CANAL
            "C212" -> Location.CLOACOGENIC_ZONE
            "C218" -> Location.RECTUM_AND_ANUS_OVERLAPPING
            "C220" -> Location.LIVER_PRIMARY
            "C221" -> Location.INTRAHEPATIC_BILE_DUCTS
            "C239" -> Location.GALL_BLADDER
            "C240" -> Location.EXTRAHEPATIC_BILE_DUCTS_NOS
            "C241" -> Location.PAPILLA_OF_VATER
            "C242" -> Location.COMMON_BILE_DUCT_DISTAL_EXTRAHEPATIC_BILE_DUCT
            "C244" -> Location.HEPATIC_DUCT_PROXIMAL_EXTRAHEPATIC_BILE_DUCTS
            "C248" -> Location.GALLBLADDER_BILE_DUCTS_OVERLAPPING
            "C249" -> Location.BILE_DUCTS_NOS
            "C250" -> Location.PANCREATIC_HEAD
            "C251" -> Location.PANCREATIC_CORPUS
            "C252" -> Location.PANCREAS_CAUDA
            "C254" -> Location.ISLETS_OF_LANGERHANS
            "C257" -> Location.OTHER_SPECIFIED_PARTS_OF_PANCREAS
            "C258" -> Location.PANCREAS_OVERLAPPING
            "C259" -> Location.PANCREAS_NOS
            "C300" -> Location.NASAL_CAVITIES
            "C310" -> Location.MAXILLARY_SINUS
            "C311" -> Location.SINUS_ETHMOIDALIS
            "C320" -> Location.GLOTTIS
            "C321" -> Location.SUPRAGLOTTIC
            "C340" -> Location.MAIN_BRONCHUS
            "C341" -> Location.LUNG_UPPER_LOBE
            "C342" -> Location.LUNG_MIDDLE_LOBE
            "C343" -> Location.LUNG_LOWER_LOBE
            "C348" -> Location.LUNG_OVERLAPPING
            "C349" -> Location.LUNG_NOS
            "C379" -> Location.THYMUS
            "C380" -> Location.HEART
            "C382" -> Location.POSTERIOR_MEDIASTINUM
            "C383" -> Location.MEDIASTINUM_NOS
            "C384" -> Location.PLEURA_NOS
            "C388" -> Location.HEART_MEDIASTINUM_AND_PLEURA_OVERLAPPING
            "C400" -> Location.SCAPULA_BONE_UPPER_EXTREMITY_BONES
            "C401" -> Location.BONE_WRIST_HAND
            "C402" -> Location.BONE_BONES_LOWER_EXTREMITY
            "C408" -> Location.OVERLYING_BONE_JOINTS_CARTILAGE_EXTREMITIES
            "C410" -> Location.BONE_SKULL_FACE
            "C411" -> Location.BONE_MANDIBLE
            "C412" -> Location.BONE_SPINE
            "C413" -> Location.BONE_RIB_STERNUM_CLAVICLE
            "C414" -> Location.BONE_OF_THE_PELVIC_BONES_SACRUM_COCCYX
            "C418" -> Location.OVERLAPPING_LOCATIONS_OF_BONE_JOINTS_CARTILAGE
            "C419" -> Location.BONE_NNO
            "C420" -> Location.BLOOD
            "C421" -> Location.BONE_MARROW
            "C422" -> Location.SPLEEN
            "C440" -> Location.SKIN_LIP
            "C441" -> Location.EYELID_SKIN
            "C442" -> Location.SKIN_EAR
            "C443" -> Location.SKIN_FACE
            "C444" -> Location.SKIN_OF_SKULL_NECK_NECK
            "C445" -> Location.SKIN_TORSO
            "C446" -> Location.SKIN_SHOULDER_ARM_HAND
            "C447" -> Location.SKIN_HIP_LEG_FOOT
            "C448" -> Location.SKIN_OVERLAPPING
            "C449" -> Location.SKIN_NOS
            "C471" -> Location.PERIPHERAL_NERVE_AUTONOMIC_NS_UPPER_EXTR_SHOULDER
            "C475" -> Location.PERIPHERAL_NERVES_AUTONOMIC_NS_PELVIS
            "C480" -> Location.RETROPERITONEUM
            "C481" -> Location.PERITONEUM_SPECIFIED_PARTS
            "C482" -> Location.PERITONEUM_NOS
            "C488" -> Location.OVERLAPPING_STRAND_RETROPERITONEUM_PERITONEUM
            "C490" -> Location.SOFT_TISSUE_HEAD_FACE_NECK
            "C491" -> Location.SOFT_TISSUE_SHOULDER_ARM_HAND
            "C492" -> Location.SOFT_TISSUE_HIP_LEG_FOOT
            "C493" -> Location.SOFT_TISSUE_THORAX
            "C494" -> Location.SOFT_TISSUE_ABDOMEN
            "C495" -> Location.SOFT_TISSUE_PELVIS
            "C496" -> Location.SOFT_TISSUE_TRUNK_NOS
            "C498" -> Location.SOFT_TISSUE_OVERLAPPING
            "C499" -> Location.SOFT_TISSUE_NOS
            "C500" -> Location.BREAST_NIPPLE_AREOLA
            "C501" -> Location.BREAST_CENTRAL_PART
            "C502" -> Location.BREAST_MEDIAL_UPPER_QUADRANT
            "C503" -> Location.BREAST_MEDIAL_LOWER_QUADRANT
            "C504" -> Location.BREAST_LATERAL_UPPER_QUADRANT
            "C505" -> Location.BREAST_LATERAL_LOWER_QUADRANT
            "C508" -> Location.BREAST_OVERLAPPING
            "C509" -> Location.BREAST_NNO
            "C510" -> Location.LABIA_MAJORA
            "C511" -> Location.LABIA_MINORA
            "C519" -> Location.VULVA_NOS
            "C529" -> Location.VAGINA_NOS
            "C530" -> Location.ENDOCERVIX
            "C539" -> Location.CERVIX_NOS
            "C540" -> Location.ISTHMUS_UTERI
            "C541" -> Location.ENDOMETRIUM
            "C542" -> Location.MYOMETRIUM
            "C548" -> Location.CORPUS_UTERI_OVERLAPPING
            "C549" -> Location.CORPUS_UTERI
            "C559" -> Location.UTERUS_NOS
            "C569" -> Location.OVARY
            "C570" -> Location.TUBA
            "C572" -> Location.LIGAMENTUM_ROTUNDUM
            "C573" -> Location.PARAMETRIUM
            "C574" -> Location.UTERINE_ADNEXA_NOS
            "C600" -> Location.PREPUTIUM
            "C601" -> Location.GLANS_PENIS
            "C602" -> Location.PENIS_BODY
            "C619" -> Location.PROSTATE
            "C621" -> Location.TESTIS_DESCENDED
            "C629" -> Location.TESTIS_NOS
            "C632" -> Location.SCROTUM
            "C637" -> Location.OTHER_SPECIFIED_LOCAL_MALE_SEXUAL_ORGANS
            "C641" -> Location.UPPER_POLE_KIDNEY
            "C642" -> Location.CENTRALLY_LOCATED_IN_THE_KIDNEY
            "C643" -> Location.LOWER_POLE_OF_KIDNEY
            "C648" -> Location.OVERLAPPING_KIDNEY_LOCATION
            "C649" -> Location.KIDNEY
            "C659" -> Location.RENAL_PELVIS
            "C669" -> Location.URETER
            "C670" -> Location.BLADDER_TRIGONUM
            "C671" -> Location.BLADDER_DOME
            "C672" -> Location.BLADDER_SIDEWALL
            "C673" -> Location.BLADDER_ANTERIOR_WALL
            "C674" -> Location.BLADDER_BACK_WALL
            "C675" -> Location.BLADDER_NECK
            "C676" -> Location.URETHRAL_ORIFICE
            "C678" -> Location.OVERLAPPING_BLADDER_LOCATION
            "C679" -> Location.BLADDER_NOS
            "C680" -> Location.URETHRA
            "C693" -> Location.CHOROIDEA
            "C700" -> Location.CEREBRAL_MENINGES
            "C701" -> Location.SPINAL_MENINGES
            "C709" -> Location.MENINGES_NOS
            "C710" -> Location.CEREBRUM
            "C711" -> Location.BRAIN_FRONTAL_LOBE
            "C712" -> Location.BRAIN_TEMPORAL_LOBE
            "C713" -> Location.BRAIN_PARIETAL_LOBE
            "C714" -> Location.BRAIN_OCCIPITAL_LOBE
            "C715" -> Location.LATERAL_VENTRICLE_THIRD_VENTRICLE
            "C716" -> Location.CEREBELLUM
            "C717" -> Location.BRAINSTEM_FOURTH_VENTRICLE
            "C718" -> Location.OVERLAPPING_BRAIN_LOCALIZATION
            "C719" -> Location.BRAIN_NOS
            "C729" -> Location.CENTRAL_NERVOUS_SYSTEM_NOS
            "C739" -> Location.THYROID
            "C740" -> Location.ADRENAL_CORTEX
            "C741" -> Location.ADRENAL_MEDULLA
            "C749" -> Location.ADRENAL_GLAND_NOS
            "C751" -> Location.PITUITARY_GLAND
            "C761" -> Location.THORAX_NOS
            "C762" -> Location.ABDOMEN_NOS
            "C763" -> Location.PELVIS_NNE
            "C767" -> Location.OTHER_POORLY_DEFINED_LOCALIZATIONS
            "C768" -> Location.OVERLAPPING_LOCALIZATION_OF_ILL_DEFINED_LOCALIZATIONS
            "C770" -> Location.LYMPH_NODES_IN_THE_HEAD_AND_NECK_AREA
            "C771" -> Location.LYMPH_NODES_INTRATHORACIC
            "C772" -> Location.LYMPH_NODES_INTRA_ABDOMINAL
            "C773" -> Location.LYMPH_NODES_AXILLA_UPPER_EXTREMITY
            "C774" -> Location.INGUINAL_LOWER_EXTREMITY_LYMPH_NODES
            "C775" -> Location.PELVIC_LYMPH_NODES
            "C778" -> Location.LYMPH_NODES_MULTIPLE_LOCATIONS
            "C779" -> Location.LYMPH_NODES_NOS
            "C809" -> Location.UNKNOWN_PRIMARY_TUMOR
            else -> throw IllegalArgumentException("Unknown SubLocation code: $code")
        }
    }
}
