package com.hartwig.actin.personalization.ncr.interpretation.mapper

import com.hartwig.actin.personalization.datamodel.diagnosis.TumorLocation

object NcrTumorLocationMapper {

    fun resolveTumorLocation(code: String): TumorLocation {
        return when (code) {
            "C000" -> TumorLocation.UPPER_LIP_LIP_RED
            "C001" -> TumorLocation.LOWER_LIP_LIP_RED
            "C019" -> TumorLocation.TONGUE_BASE
            "C021" -> TumorLocation.TONGUE_TIP_AND_SIDE_EDGE
            "C022" -> TumorLocation.TONGUE_VENTRAL_SURFACE
            "C024" -> TumorLocation.TONSILLA_LINGUALIS
            "C031" -> TumorLocation.GUMS_LOWER_JAW
            "C040" -> TumorLocation.FLOOR_OF_MOUTH_ANTERIOR_PART
            "C041" -> TumorLocation.FLOOR_OF_MOUTH_LATERAL_PART
            "C050" -> TumorLocation.HARD_PALATE
            "C051" -> TumorLocation.SOFT_PALATE
            "C052" -> TumorLocation.UVULA
            "C060" -> TumorLocation.CHEEK_MUCOSA
            "C062" -> TumorLocation.RETROMOLAR_AREA
            "C079" -> TumorLocation.GLANDULA_PAROTID
            "C080" -> TumorLocation.GLANDULA_SUBMANDIBULARIS
            "C090" -> TumorLocation.TONSILNIS
            "C091" -> TumorLocation.TONSIL_FOLDS
            "C099" -> TumorLocation.TONSILS
            "C100" -> TumorLocation.VALLECULA
            "C103" -> TumorLocation.POSTERIOR_OROPHARYNGEAL_WALL
            "C111" -> TumorLocation.NASOPHARYNX_POSTERIOR_WALL
            "C119" -> TumorLocation.NASOPHARYNX_NOS
            "C129" -> TumorLocation.SINUS_PYRIFORM
            "C130" -> TumorLocation.POSTCRICOID_REGION
            "C131" -> TumorLocation.ARYEPIGLOTTIC_FOLD
            "C139" -> TumorLocation.HYPOPHARYNX_NOS
            "C148" -> TumorLocation.LIP_ORAL_CAVITY_PHARYNX_OVERLAPPING
            "C153" -> TumorLocation.ESOPHAGUS_UPPER_THIRD
            "C154" -> TumorLocation.ESOPHAGUS_MIDDLE_THIRD
            "C155" -> TumorLocation.ESOPHAGUS_LOWER_THIRD
            "C159" -> TumorLocation.ESOPHAGUS_NOS
            "C160" -> TumorLocation.GASTRIC_CARDIA
            "C161" -> TumorLocation.GASTRIC_FUNDUS
            "C162" -> TumorLocation.GASTRIC_CORPUS
            "C163" -> TumorLocation.GASTRIC_ANTRUM_PYLORI
            "C165" -> TumorLocation.GASTRIC_SMALL_CURVATURE_NOS
            "C166" -> TumorLocation.GASTRIC_GREATER_CURVATURE_NOS
            "C167" -> TumorLocation.GASTROESOPHAGEAL_JUNCTION
            "C168" -> TumorLocation.STOMACH_OVERHANG
            "C169" -> TumorLocation.STOMACH_NOS
            "C170" -> TumorLocation.DUODENUM
            "C171" -> TumorLocation.JEJUNUM
            "C172" -> TumorLocation.ILEUM
            "C178" -> TumorLocation.SMALL_INTESTINE_OVERLAPPING
            "C179" -> TumorLocation.SMALL_INTESTINE_NOS
            "C180" -> TumorLocation.COECUM
            "C181" -> TumorLocation.APPENDIX
            "C182" -> TumorLocation.ASCENDING_COLON
            "C183" -> TumorLocation.FLEXURA_HEPATICA
            "C184" -> TumorLocation.TRANSVERSE_COLON
            "C185" -> TumorLocation.FLEXURA_LIENALIS
            "C186" -> TumorLocation.DESCENDING_COLON
            "C187" -> TumorLocation.SIGMOID_COLON
            "C188" -> TumorLocation.COLON_OVERLAPPING
            "C189" -> TumorLocation.COLON_NOS
            "C199" -> TumorLocation.RECTOSIGMOID
            "C209" -> TumorLocation.RECTUM
            "C210" -> TumorLocation.ANUS_NOS
            "C211" -> TumorLocation.ANAL_CANAL
            "C212" -> TumorLocation.CLOACOGENIC_ZONE
            "C218" -> TumorLocation.RECTUM_AND_ANUS_OVERLAPPING
            "C220" -> TumorLocation.LIVER_PRIMARY
            "C221" -> TumorLocation.INTRAHEPATIC_BILE_DUCTS
            "C239" -> TumorLocation.GALL_BLADDER
            "C240" -> TumorLocation.EXTRAHEPATIC_BILE_DUCTS_NOS
            "C241" -> TumorLocation.PAPILLA_OF_VATER
            "C242" -> TumorLocation.COMMON_BILE_DUCT_DISTAL_EXTRAHEPATIC_BILE_DUCT
            "C244" -> TumorLocation.HEPATIC_DUCT_PROXIMAL_EXTRAHEPATIC_BILE_DUCTS
            "C248" -> TumorLocation.GALLBLADDER_BILE_DUCTS_OVERLAPPING
            "C249" -> TumorLocation.BILE_DUCTS_NOS
            "C250" -> TumorLocation.PANCREATIC_HEAD
            "C251" -> TumorLocation.PANCREATIC_CORPUS
            "C252" -> TumorLocation.PANCREAS_CAUDA
            "C254" -> TumorLocation.ISLETS_OF_LANGERHANS
            "C257" -> TumorLocation.OTHER_SPECIFIED_PARTS_OF_PANCREAS
            "C258" -> TumorLocation.PANCREAS_OVERLAPPING
            "C259" -> TumorLocation.PANCREAS_NOS
            "C300" -> TumorLocation.NASAL_CAVITIES
            "C310" -> TumorLocation.MAXILLARY_SINUS
            "C311" -> TumorLocation.SINUS_ETHMOIDALIS
            "C320" -> TumorLocation.GLOTTIS
            "C321" -> TumorLocation.SUPRAGLOTTIC
            "C340" -> TumorLocation.MAIN_BRONCHUS
            "C341" -> TumorLocation.LUNG_UPPER_LOBE
            "C342" -> TumorLocation.LUNG_MIDDLE_LOBE
            "C343" -> TumorLocation.LUNG_LOWER_LOBE
            "C348" -> TumorLocation.LUNG_OVERLAPPING
            "C349" -> TumorLocation.LUNG_NOS
            "C379" -> TumorLocation.THYMUS
            "C380" -> TumorLocation.HEART
            "C382" -> TumorLocation.POSTERIOR_MEDIASTINUM
            "C383" -> TumorLocation.MEDIASTINUM_NOS
            "C384" -> TumorLocation.PLEURA_NOS
            "C388" -> TumorLocation.HEART_MEDIASTINUM_AND_PLEURA_OVERLAPPING
            "C400" -> TumorLocation.SCAPULA_BONE_UPPER_EXTREMITY_BONES
            "C401" -> TumorLocation.BONE_WRIST_HAND
            "C402" -> TumorLocation.BONE_BONES_LOWER_EXTREMITY
            "C408" -> TumorLocation.OVERLYING_BONE_JOINTS_CARTILAGE_EXTREMITIES
            "C410" -> TumorLocation.BONE_SKULL_FACE
            "C411" -> TumorLocation.BONE_MANDIBLE
            "C412" -> TumorLocation.BONE_SPINE
            "C413" -> TumorLocation.BONE_RIB_STERNUM_CLAVICLE
            "C414" -> TumorLocation.BONE_OF_THE_PELVIC_BONES_SACRUM_COCCYX
            "C418" -> TumorLocation.OVERLAPPING_LOCATIONS_OF_BONE_JOINTS_CARTILAGE
            "C419" -> TumorLocation.BONE_NNO
            "C420" -> TumorLocation.BLOOD
            "C421" -> TumorLocation.BONE_MARROW
            "C422" -> TumorLocation.SPLEEN
            "C440" -> TumorLocation.SKIN_LIP
            "C441" -> TumorLocation.EYELID_SKIN
            "C442" -> TumorLocation.SKIN_EAR
            "C443" -> TumorLocation.SKIN_FACE
            "C444" -> TumorLocation.SKIN_OF_SKULL_NECK_NECK
            "C445" -> TumorLocation.SKIN_TORSO
            "C446" -> TumorLocation.SKIN_SHOULDER_ARM_HAND
            "C447" -> TumorLocation.SKIN_HIP_LEG_FOOT
            "C448" -> TumorLocation.SKIN_OVERLAPPING
            "C449" -> TumorLocation.SKIN_NOS
            "C471" -> TumorLocation.PERIPHERAL_NERVE_AUTONOMIC_NS_UPPER_EXTR_SHOULDER
            "C475" -> TumorLocation.PERIPHERAL_NERVES_AUTONOMIC_NS_PELVIS
            "C480" -> TumorLocation.RETROPERITONEUM
            "C481" -> TumorLocation.PERITONEUM_SPECIFIED_PARTS
            "C482" -> TumorLocation.PERITONEUM_NOS
            "C488" -> TumorLocation.OVERLAPPING_STRAND_RETROPERITONEUM_PERITONEUM
            "C490" -> TumorLocation.SOFT_TISSUE_HEAD_FACE_NECK
            "C491" -> TumorLocation.SOFT_TISSUE_SHOULDER_ARM_HAND
            "C492" -> TumorLocation.SOFT_TISSUE_HIP_LEG_FOOT
            "C493" -> TumorLocation.SOFT_TISSUE_THORAX
            "C494" -> TumorLocation.SOFT_TISSUE_ABDOMEN
            "C495" -> TumorLocation.SOFT_TISSUE_PELVIS
            "C496" -> TumorLocation.SOFT_TISSUE_TRUNK_NOS
            "C498" -> TumorLocation.SOFT_TISSUE_OVERLAPPING
            "C499" -> TumorLocation.SOFT_TISSUE_NOS
            "C500" -> TumorLocation.BREAST_NIPPLE_AREOLA
            "C501" -> TumorLocation.BREAST_CENTRAL_PART
            "C502" -> TumorLocation.BREAST_MEDIAL_UPPER_QUADRANT
            "C503" -> TumorLocation.BREAST_MEDIAL_LOWER_QUADRANT
            "C504" -> TumorLocation.BREAST_LATERAL_UPPER_QUADRANT
            "C505" -> TumorLocation.BREAST_LATERAL_LOWER_QUADRANT
            "C508" -> TumorLocation.BREAST_OVERLAPPING
            "C509" -> TumorLocation.BREAST_NNO
            "C510" -> TumorLocation.LABIA_MAJORA
            "C511" -> TumorLocation.LABIA_MINORA
            "C519" -> TumorLocation.VULVA_NOS
            "C529" -> TumorLocation.VAGINA_NOS
            "C530" -> TumorLocation.ENDOCERVIX
            "C539" -> TumorLocation.CERVIX_NOS
            "C540" -> TumorLocation.ISTHMUS_UTERI
            "C541" -> TumorLocation.ENDOMETRIUM
            "C542" -> TumorLocation.MYOMETRIUM
            "C548" -> TumorLocation.CORPUS_UTERI_OVERLAPPING
            "C549" -> TumorLocation.CORPUS_UTERI
            "C559" -> TumorLocation.UTERUS_NOS
            "C569" -> TumorLocation.OVARY
            "C570" -> TumorLocation.TUBA
            "C572" -> TumorLocation.LIGAMENTUM_ROTUNDUM
            "C573" -> TumorLocation.PARAMETRIUM
            "C574" -> TumorLocation.UTERINE_ADNEXA_NOS
            "C600" -> TumorLocation.PREPUTIUM
            "C601" -> TumorLocation.GLANS_PENIS
            "C602" -> TumorLocation.PENIS_BODY
            "C619" -> TumorLocation.PROSTATE
            "C621" -> TumorLocation.TESTIS_DESCENDED
            "C629" -> TumorLocation.TESTIS_NOS
            "C632" -> TumorLocation.SCROTUM
            "C637" -> TumorLocation.OTHER_SPECIFIED_LOCAL_MALE_SEXUAL_ORGANS
            "C641" -> TumorLocation.UPPER_POLE_KIDNEY
            "C642" -> TumorLocation.CENTRALLY_LOCATED_IN_THE_KIDNEY
            "C643" -> TumorLocation.LOWER_POLE_OF_KIDNEY
            "C648" -> TumorLocation.OVERLAPPING_KIDNEY_LOCATION
            "C649" -> TumorLocation.KIDNEY
            "C659" -> TumorLocation.RENAL_PELVIS
            "C669" -> TumorLocation.URETER
            "C670" -> TumorLocation.BLADDER_TRIGONUM
            "C671" -> TumorLocation.BLADDER_DOME
            "C672" -> TumorLocation.BLADDER_SIDEWALL
            "C673" -> TumorLocation.BLADDER_ANTERIOR_WALL
            "C674" -> TumorLocation.BLADDER_BACK_WALL
            "C675" -> TumorLocation.BLADDER_NECK
            "C676" -> TumorLocation.URETHRAL_ORIFICE
            "C678" -> TumorLocation.OVERLAPPING_BLADDER_LOCATION
            "C679" -> TumorLocation.BLADDER_NOS
            "C680" -> TumorLocation.URETHRA
            "C693" -> TumorLocation.CHOROIDEA
            "C700" -> TumorLocation.CEREBRAL_MENINGES
            "C701" -> TumorLocation.SPINAL_MENINGES
            "C709" -> TumorLocation.MENINGES_NOS
            "C710" -> TumorLocation.CEREBRUM
            "C711" -> TumorLocation.BRAIN_FRONTAL_LOBE
            "C712" -> TumorLocation.BRAIN_TEMPORAL_LOBE
            "C713" -> TumorLocation.BRAIN_PARIETAL_LOBE
            "C714" -> TumorLocation.BRAIN_OCCIPITAL_LOBE
            "C715" -> TumorLocation.LATERAL_VENTRICLE_THIRD_VENTRICLE
            "C716" -> TumorLocation.CEREBELLUM
            "C717" -> TumorLocation.BRAINSTEM_FOURTH_VENTRICLE
            "C718" -> TumorLocation.OVERLAPPING_BRAIN_LOCALIZATION
            "C719" -> TumorLocation.BRAIN_NOS
            "C729" -> TumorLocation.CENTRAL_NERVOUS_SYSTEM_NOS
            "C739" -> TumorLocation.THYROID
            "C740" -> TumorLocation.ADRENAL_CORTEX
            "C741" -> TumorLocation.ADRENAL_MEDULLA
            "C749" -> TumorLocation.ADRENAL_GLAND_NOS
            "C751" -> TumorLocation.PITUITARY_GLAND
            "C761" -> TumorLocation.THORAX_NOS
            "C762" -> TumorLocation.ABDOMEN_NOS
            "C763" -> TumorLocation.PELVIS_NNE
            "C767" -> TumorLocation.OTHER_POORLY_DEFINED_LOCALIZATIONS
            "C768" -> TumorLocation.OVERLAPPING_LOCALIZATION_OF_ILL_DEFINED_LOCALIZATIONS
            "C770" -> TumorLocation.LYMPH_NODES_IN_THE_HEAD_AND_NECK_AREA
            "C771" -> TumorLocation.LYMPH_NODES_INTRATHORACIC
            "C772" -> TumorLocation.LYMPH_NODES_INTRA_ABDOMINAL
            "C773" -> TumorLocation.LYMPH_NODES_AXILLA_UPPER_EXTREMITY
            "C774" -> TumorLocation.INGUINAL_LOWER_EXTREMITY_LYMPH_NODES
            "C775" -> TumorLocation.PELVIC_LYMPH_NODES
            "C778" -> TumorLocation.LYMPH_NODES_MULTIPLE_LOCATIONS
            "C779" -> TumorLocation.LYMPH_NODES_NOS
            "C809" -> TumorLocation.UNKNOWN_PRIMARY_TUMOR
            else -> throw IllegalArgumentException("Unknown TumorLocation code: $code")
        }
    }
}
