package com.hartwig.actin.personalization.ncr.interpretation.mapper

import com.hartwig.actin.personalization.datamodel.TreatmentName

fun resolveTreatmentName(code: String): TreatmentName {
    return when (code) {
        "214000" -> TreatmentName.EXTERNAL_RADIOTHERAPY_WITH_SENSITIZER
        "420INT" -> TreatmentName.INTENSIVE_CHEMOTHERAPY
        "420000" -> TreatmentName.SYSTEMIC_CHEMOTHERAPY
        "421000" -> TreatmentName.TAXANE_CONTAINING_CHEMOTHERAPY
        "422000" -> TreatmentName.PLATINUM_CONTAINING_CHEMOTHERAPY
        "426000" -> TreatmentName.ANTHRACYCLINE_CONTAINING_CHEMOTHERAPY
        "427000" -> TreatmentName.ANTHRACYCLINE_AND_TAXANE_CONTAINING_CHEMOTHERAPY
        "690420" -> TreatmentName.CHEMOTHERAPY_ABROAD
        "L01AA01" -> TreatmentName.CYCLOPHOSPHAMIDE
        "L01AA02" -> TreatmentName.CHLORAMBUCIL_LEUKERAN
        "L01AA03" -> TreatmentName.MELPHALAN
        "L01AA09" -> TreatmentName.BENDAMUSTINE
        "L01BA01" -> TreatmentName.METHOTREXATE
        "L01BA03" -> TreatmentName.RALTITREXED
        "L01BA04" -> TreatmentName.PEMETREXED
        "L01BB04" -> TreatmentName.CLADRIBINE
        "L01BC01" -> TreatmentName.CYTARABINE
        "L01BC02" -> TreatmentName.FLUOROURACIL
        "L01BC03" -> TreatmentName.TEGAFUR
        "L01BC05" -> TreatmentName.GEMCITABINE_SYSTEMIC
        "L01BC06" -> TreatmentName.CAPECITABINE
        "L01BC53" -> TreatmentName.TEGAFUR_GIMERACIL_OTERACIL
        "L01BC59" -> TreatmentName.TRIFLURIDINE_TIPIRACIL
        "L01CA02" -> TreatmentName.VINCRISTINE
        "L01CB01" -> TreatmentName.ETOPOSIDE
        "L01CD01" -> TreatmentName.PACLITAXEL
        "L01CD02" -> TreatmentName.DOCETAXEL
        "L01CE02" -> TreatmentName.IRINOTECAN
        "L01DB01" -> TreatmentName.DOXORUBICIN_ADRIAMYCIN
        "L01DB02" -> TreatmentName.DAUNORUBICIN
        "L01DB03" -> TreatmentName.EPIRUBICIN_SYSTEMIC
        "L01DC03" -> TreatmentName.MITOMYCIN_SYSTEMIC
        "L01XA01" -> TreatmentName.CISPLATIN
        "L01XA02" -> TreatmentName.CARBOPLATIN
        "L01XA03" -> TreatmentName.OXALIPLATIN
        "L01XX05" -> TreatmentName.HYDROREA_HYDROXYUREA
        "L01XX27" -> TreatmentName.ATO_ARSENIC_TRIOXIDE
        "500000" -> TreatmentName.HORMONAL_THERAPY_NNO
        "510000" -> TreatmentName.HORMONAL_THERAPY_THROUGH_SURGERY
        "540000" -> TreatmentName.DRUG_HORMONAL_THERAPY
        "H01CB02" -> TreatmentName.OCTREOTIDE
        "L02AB01" -> TreatmentName.MEGESTROL_MEGACE
        "L02AE" -> TreatmentName.GONADORELIN_AGONISTS_LHRH
        "L02AE02" -> TreatmentName.LEUPRORELIN_ELIGARD_LUCRIN
        "L02AE03" -> TreatmentName.GOSERELIN_ZOLADEX
        "L02AE04" -> TreatmentName.TRIPTORELIN_PAMORELIN
        "L02BA01" -> TreatmentName.TAMOXIFEN
        "L02BB" -> TreatmentName.ANTI_ANDROGENS
        "L02BB03" -> TreatmentName.BICALUTAMIDE_BILURON_CASODEX
        "L02BG" -> TreatmentName.AROMATASE_INHIBITORS
        "L02BG03" -> TreatmentName.ANASTROZOLE
        "L02BG04" -> TreatmentName.LETROZOLE_FEMARA
        "L02BX" -> TreatmentName.GONADORELIN_ANTAGONISTS_LHRH
        "L02BX03" -> TreatmentName.ABIRATERONE_ZYTIGA_AND_PREDNISONE
        "H02AB02" -> TreatmentName.DEXAMETHASONE
        "H02AB07" -> TreatmentName.PREDNISONE
        "L03AB04" -> TreatmentName.INTERFERON_ALPHA_2A
        "430000" -> TreatmentName.TARGETED_THERAPY
        "433000" -> TreatmentName.ANGIOGENESIS_INHIBITOR
        "690430" -> TreatmentName.TARGETED_THERAPY_ABROAD
        "699005" -> TreatmentName.STUDY_MEDICATION_IMMUNOTHERAPY
        "L01E" -> TreatmentName.PROTEIN_KINASE_INHIBITORS
        "L01EA01" -> TreatmentName.IMATINIB
        "L01EB02" -> TreatmentName.ERLOTINIB
        "L01EC01" -> TreatmentName.VEMURAFENIB
        "L01EC02" -> TreatmentName.DABRAFENIB
        "L01EC03" -> TreatmentName.ENCORAFENIB
        "L01EE01" -> TreatmentName.TRAMETINIB
        "L01EE03" -> TreatmentName.BINIMETINIB
        "L01EJ01" -> TreatmentName.RUXOLITINIB
        "L01EK01" -> TreatmentName.AXITINIB
        "L01EL01" -> TreatmentName.IBRUTINIB
        "L01EX03" -> TreatmentName.PAZOPANIB
        "L01EX07" -> TreatmentName.CABOZANTINIB
        "L01F" -> TreatmentName.MONOCLONAL_ANTIBODIES
        "L01FA01" -> TreatmentName.RITUXIMAB
        "L01FD01" -> TreatmentName.TRASTUZUMAB_HERCEPTIN
        "L01FD02" -> TreatmentName.PERTUZUMAB
        "L01FE01" -> TreatmentName.CETUXIMAB
        "L01FE02" -> TreatmentName.PANITUMUMAB
        "L01FF01" -> TreatmentName.NIVOLUMAB
        "L01FF02" -> TreatmentName.PEMBROLIZUMAB
        "L01FF03" -> TreatmentName.DURVALUMAB
        "L01FF05" -> TreatmentName.ATEZOLIZUMAB
        "L01FG01" -> TreatmentName.BEVACIZUMAB
        "L01FX04" -> TreatmentName.IPILIMUMAB
        "L01FX20" -> TreatmentName.TREMELIMUMAB
        "L01XG01" -> TreatmentName.BORTEZOMIB
        "L04AX02" -> TreatmentName.THALIDOMIDE
        "L04AX04" -> TreatmentName.LENALIDOMIDE
        else -> throw IllegalArgumentException("Unknown treatment code: $code")
    }
}