cpct_colorectal_treatment_curation <- function(data_set) {

data_set <- add_column(data_set, treatmentCurated = ifelse((grepl("Oxaliplatin", data_set$treatment) & grepl("Bevacizumab", data_set$treatment) & grepl("Capecitabine", data_set$treatment) &! grepl("Fluorouracil", data_set$treatment) &! grepl("Irinotecan", data_set$treatment)), "CAPOX-B", data_set$treatment), .after = "treatment")
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated) & grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated)), "CAPOX", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) & grepl("S1", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated)), "Capecitabine+Bevacizumab+S1", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("S1", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated)), "Capecitabine+Bevacizumab", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("S1", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated)), "Capecitabine", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Trifluridine", data_set$treatmentCurated) | grepl("Tipiracil", data_set$treatmentCurated)), "Trifluridine", data_set$treatmentCurated)) 
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) & grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated)), "FOLFOXIRI", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) & grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated)), "FOLFOXIRI-B", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) & grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated) & grepl("Panitumumab", data_set$treatmentCurated)), "FOLFOX-P", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) & grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated)), "FOLFOX", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) & grepl("Oxaliplatin", data_set$treatmentCurated) &! grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated)), "FOLFOX-B", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "FOLFIRI", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "FOLFIRI-B", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "FOLFIRI-B", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((!grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) &! grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "Irinotecan+Bevacizumab", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((!grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) & grepl("Capecitabine", data_set$treatmentCurated) &! grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "CAPIRI", data_set$treatmentCurated))
data_set <- mutate(data_set, treatmentCurated = ifelse((!grepl("Fluorouracil", data_set$treatmentCurated) &! grepl("Oxaliplatin", data_set$treatmentCurated) & grepl("Irinotecan", data_set$treatmentCurated) & grepl("Capecitabine", data_set$treatmentCurated) & grepl("Bevacizumab", data_set$treatmentCurated) &! grepl("Panitumumab", data_set$treatmentCurated)), "CAPIRI-B", data_set$treatmentCurated))

}