USE actin_cairo;

ALTER TABLE C2_patient
CHANGE `primaryTumorSite` `primaryTumorSite` INT,
CHANGE `primaryTumorInSitu` `primaryTumorInSitu` INT,
CHANGE `mhcd` `concomittantDisease` INT NULL,
CHANGE `mccds` `concomittantDiseaseComments` VARCHAR(255),
CHANGE `priorSurgery` `priorSurgery` INT,
CHANGE `priorSurgerySpecification` `priorSurgerySpecification1` VARCHAR(255) ,
CHANGE `PS2s` `priorSurgerySpecification2` VARCHAR(255),
CHANGE `PS3s` `priorSurgerySpecification3` VARCHAR(255),
CHANGE `PS4s` `priorSurgerySpecification4` VARCHAR(255),
CHANGE `PS5s` `priorSurgerySpecification5` VARCHAR(255),
CHANGE `DPS1dt` `priorSurgeryDate1` VARCHAR(255),
CHANGE `DPS2dt` `priorSurgeryDate2` VARCHAR(255),
CHANGE `DPS3dt` `priorSurgeryDate3` VARCHAR(255),
CHANGE `DPS4dt` `priorSurgeryDate4` VARCHAR(255),
CHANGE `DPS5dt` `priorSurgeryDate5` VARCHAR(255),
CHANGE `PCd` `priorAdjuvantChemotherapy` VARCHAR(255),
CHANGE `PCs` `priorAdjuvantChemotherapySpecification` VARCHAR(255),
CHANGE `DPCstdt` `priorAdjuvantChemotherapyStartDate` VARCHAR(255),
CHANGE `DPCenddt` `priorAdjuvantChemotherapyEndDate` VARCHAR(255),
CHANGE `PRd` `priorRadiotherapy` INT NULL,
CHANGE `PRs` `priorRadiotherapySpecification` VARCHAR(255),
CHANGE `DPRstdt` `priorRadiotherapyDateStart` VARCHAR(255),
CHANGE `DPRenddt` `priorRadiotherapyDateEnd` VARCHAR(255),
CHANGE `PRGy` `priorRadiotherapyDose` FLOAT,
CHANGE `DDiagdt` `dateOfHistologicalDiagnosis` VARCHAR(255),
CHANGE `Ddismt` `dateOfDistantMetastasis` VARCHAR(255),
CHANGE `DisStat` `distantMetastasisStatus` INT NULL;

ALTER TABLE C2_cycles CHANGE `Best overall response` `Best overall response` INT NULL;

ALTER TABLE C2_outcome
CHANGE `OS_event` `OS_event` INT NULL,
CHANGE `upd_pfs_event` `upd_pfs_event` INT NULL;


ALTER TABLE C3_patient
CHANGE `DMDTCBIRDT` `birthdate` VARCHAR(255),
CHANGE `DMGENDER` `sex` INT NULL,
CHANGE `VSORRESWEIGHT` `weight` FLOAT,
CHANGE `VSORRESHEIGHT` `height` FLOAT,
CHANGE `VSORRESWHO` `who` FLOAT,
CHANGE `MHOCCURMHCD` `comorbidities` INT NULL,
CHANGE `MHTERMMHCDS` `comorbiditiesSpecification` VARCHAR(255),
CHANGE `DMSMOKING` `smoking` INT NULL,
CHANGE `SCDTCDIAGDT` `dateDiagnosis` VARCHAR(255),
CHANGE `SCORRESTMN` `tnmClassification` INT NULL,
CHANGE `SCORRESSITE` `sitePrimaryTumor` INT NULL,
CHANGE `SCDTCDISMETDT` `firstMetastasesDate` VARCHAR(255),

CHANGE `CMOCCURPMB` `metastasesBiopsy` INT NULL,
CHANGE `CMDTCPMBDT` `metastasesBiopsyDate` VARCHAR(255),
CHANGE `LBORRESPMBTNR` `metastasesBiopsyPath` VARCHAR(255),
CHANGE `LBPMBHOSP` `metastasesBiopsyHospital` VARCHAR(255),

CHANGE `CMOCCURPT` `resectionPrimaryTumor` INT NULL,
CHANGE `CMDTCPTDT` `resectionPrimaryTumorDate` VARCHAR(255),
CHANGE `LBORRESPTTNR` `resectionPrimaryTumorPath` VARCHAR(255),
CHANGE `LBPTHOSP` `resectionPrimaryTumorHospital` VARCHAR(255),

CHANGE `CMOCCURPMR` `priorResectionMetastases` INT NULL,
CHANGE `CMDTCPMRDT` `priorResectionMetastasesDate` VARCHAR(255),
CHANGE `CMTRTPMRSITE` `priorResectionMetastasesSite` INT NULL,
CHANGE `CMSCATPMRSITES` `priorResectionMetastasesSites` VARCHAR(255),
CHANGE `LBORRESPMRTNR` `priorResectionMetastasesPath` VARCHAR(255),
CHANGE `LBPMRHOSP` `priorResectionMetastasesHospital` VARCHAR(255),


CHANGE `CMOCCURPC` `adjuvantChemo` INT NULL,
CHANGE `CMTRTPCS` `adjuvantChemoDrugs` VARCHAR(255),
CHANGE `CMSDTCPCST` `adjuvantChemoDateStart` VARCHAR(255),
CHANGE `CMENDTCPCENDDT` `adjuvantChemoDateLast` VARCHAR(255),

CHANGE `CMOCCURPR` `radiotherapy` INT NULL,
CHANGE `CMTRTPRSITE` `radiotherapySite` VARCHAR(255),
CHANGE `CMSDTCPRST` `radiotherapyDateStart` VARCHAR(255),
CHANGE `CMENDTCPRENDDT` `radiotherapyDateLast` VARCHAR(255),
CHANGE `CMDOSEPRTD` `radiotherapyDose` FLOAT,

CHANGE `EXSDTCICSTDT` `dateStartTreatment` VARCHAR(255),
CHANGE `EXSDTCIC6CSTDT` `dateStartTreatmentCycle6`VARCHAR(255),
CHANGE `EXOCCURICCR` `doseReductionTreatmentCap` INT NULL,
CHANGE `EXORRESICCRP` `doseReductionTreatmentCapPercentage` FLOAT,
CHANGE `EXDOSEICCLDD` `doseReductionTreatmentCapDateLast` VARCHAR(255),
CHANGE `EXOCCURICOR` `doseReductionTreatmentOxa` INT NULL,
CHANGE `EXORRESICORP` `doseReductionTreatmentOxaPercentage` FLOAT,
CHANGE `EXDOSEICOLD` `doseReductionTreatmentOxaDateLast`VARCHAR(255),
CHANGE `EXOCCURICD` `treatmentDelay` INT NULL,
CHANGE `EXORRESICDMAX` `TreatmentDelayWeeks`FLOAT,
CHANGE `EXOCCURICB6C` `bevacizumab6Cycles`INT NULL,
CHANGE `SCDTCRESPBDT` `responseAssessmentDateBeforeTreatment` VARCHAR(255),
CHANGE `SCDTCRESPA3DT` `responseAssessmentDateAfterThreeCycles` VARCHAR(255),
CHANGE `SCORRESRESP3C` `responseAssessmentSiteAfterThreeCycles` INT NULL,
CHANGE `SCDTCRESPA6DT` `responseAssessmentDateAfterSixCycles` VARCHAR(255),
CHANGE `SCORRESRESP6C` `responseAssessmentSiteAfterSixCycle` INT NULL;

ALTER TABLE C3_mutations
CHANGE `BRAFV600E.combined` `BRAFV600E.combined` INT NULL,
CHANGE `KRAS.combined` `KRAS.combined` INT NULL;

ALTER TABLE C3_endtreatment
CHANGE `EXENDTCOXLADMDTE` `treatmentOxaDateLast` VARCHAR(255),
CHANGE `EXENDTCBELACMDTE` `treatmentBevaDateLast` VARCHAR(255),
CHANGE `EXENDTCCALADMDTE` `treatmentCapDateLast` VARCHAR(255),
CHANGE `EXDOSTXTCYCLESGE` `totalCyclesTreatment` INT NULL,
CHANGE `EXORRESRDISC` `protocolDiscontinuationReason`INT NULL,
CHANGE `EXORRESRDISCS` `protocolDiscontinuationSpecifications` VARCHAR(255),
CHANGE `SCSDTCCR1DT` `crDateFirstDocumented` VARCHAR(255),
CHANGE `SCENDTCCR2DT` `crDateConfirmed` VARCHAR(255),
CHANGE `SCSDTCPR1DT` `prDateFirstDocumented` VARCHAR(255),
CHANGE `SCSDTCPR2DT` `prDateConfirmed` VARCHAR(255),
CHANGE `SCSDTCSD1DT` `sdDateFirstDocumented` VARCHAR(255),
CHANGE `SCDTCPD1DT` `progressionFirstDocumented` VARCHAR(255),
CHANGE `SCORRESBORESP` `bestOverallResponseAfterReintroductionTreatment` INT,
CHANGE `SCORRESBORESPS` `bestOverallResponseAfterReintroductionTreatmentSpecification`VARCHAR(255),
CHANGE `VSDTCLFUPDT` `dateLastAliveStatus` VARCHAR(255),
CHANGE `VSORRESPATSTATE` `survivalStatus` INT NULL,
CHANGE `VSORRESDCAUSE` `deathCause` INT NULL,
CHANGE `VSORRESDCAUSES` `deathToxicityCaseSpecification` VARCHAR(255),
CHANGE `COEXENDMTD` `deathOtherCaseSpecification` VARCHAR(255);


ALTER TABLE C3_outcome
CHANGE `SCSDTCPD1DOCDT` `firstProgressionDate` VARCHAR(255),
CHANGE `SCORRESPDDIAG` `firstProgressionMethod` FLOAT,
CHANGE `SCENDTCPDCTDT` `firstProgressionCtDate` VARCHAR(255),
CHANGE `EXDOSTXTCYCLESG` `totalCyclesMaintenanceTherapy` FLOAT,
CHANGE `EXENDTCBELADMDT` `treatmentBevaDateLast` VARCHAR(255),
CHANGE `EXENDTCCALADMDT` `treatmentCapDateLast` VARCHAR(255),
CHANGE `EXORRESRSCHTRT` `reasonStopObservationTreatment` INT NULL,
CHANGE `EXORRESRSCHTRTS` `reasonStopObservationTreatmentSpecification` VARCHAR(255),
CHANGE `COEXENDMAINT` `reasonStopObservationTreatmentComments` VARCHAR(255),
CHANGE `EXORRESNEXSTEP` `nextTreatment` INT NULL,
CHANGE `EXORRESNEXTEP` `nextTreatmentSpecification` VARCHAR(255),
CHANGE `VSORRESPATSTAT` `survivalStatus` INT NULL,
CHANGE `VSDTCDEATHDT` `dateLastAliveStatus` VARCHAR(255),
CHANGE `VSORRESCDEATH` `deathCause` INT NULL,
CHANGE `VSORRESCDEATHS` `deathCauseSpecification` VARCHAR(255);

ALTER TABLE C3_tumor
CHANGE `TMTESTTISPMM` `primaryTumorSiteMethod` INT NULL,
CHANGE `TMORRESTISPSI` `primaryTumorSiteInvolved` INT NULL,
CHANGE `TMORRESTISPTL` `primaryTumorSiteLesionMeasurable` INT NULL,
CHANGE `TMSCATTISPCM` `primaryTumorSiteComments` VARCHAR(255),
CHANGE `TMTESTTILNMM` `lymphNodeMethod`INT NULL,
CHANGE `TMORRESTTILNSI` `lymphNodeInvolved` INT NULL,
CHANGE `TMORRESTILNTL` `lymphNodeLesionMeasurable` INT NULL,
CHANGE `TMSCATTILNCM` `lymphNodeComments` VARCHAR(255),
CHANGE `TMTESTTILUMM` `lungMethod` INT NULL,
CHANGE `TMORRESTILUSI` `lungInvolved` INT NULL,
CHANGE `TMORRESTILUTL` `lungLesionMeasurable` INT NULL,
CHANGE `TMSCATTILUCM` `lungLesionComments` VARCHAR(255),
CHANGE `TMTESTTILIMM` `liverMethod` INT NULL,
CHANGE `TMORRESTILISI` `liverInvolved` INT NULL,
CHANGE `TMORRESTILITL` `liverLesionMeasurable` INT NULL,
CHANGE `TMSCATTILINCM` `liverComments` VARCHAR(255),
CHANGE `TMTESTTISKMM` `skinMethod` INT NULL,
CHANGE `TMORRESTISKSI` `skinInvolved` INT NULL,
CHANGE `TMORRESTISKTL` `skinLesionMeasurable` INT NULL,
CHANGE `TMSCATTISKCM` `skinLesionComments` VARCHAR(255),
CHANGE `TMTESTTISTMM` `softTissueMethod` INT NULL,
CHANGE `TMORRESTISTSI` `softTissueInvolved` INT NULL,
CHANGE `TMORRESTISTTL` `softTissueLesionMeasurable`INT NULL,
CHANGE `TMSCATTISTCM` `softTissueComments` VARCHAR(255),
CHANGE `TMTESTTIBNMM` `boneMethod` INT NULL,
CHANGE `TMTESTTIBNSI` `boneInvolved` INT NULL,
CHANGE `TMSCATTIBNCM` `boneComments` VARCHAR(255),
CHANGE `TMTESTTIASMM` `ascitisMethod` INT NULL,
CHANGE `TMORRESTIASSI` `ascitisInvolved` INT NULL,
CHANGE `TMORRESTIASMR` `ascitisMalignancyRelated` INT NULL,
CHANGE `TMTESTTIPEMM` `pleuralEffusionMethod` INT NULL,
CHANGE `TMORRESTIPESI` `pleuralEffusionInvolved` INT NULL,
CHANGE `TMORRESTIPEMR` `pleuralEffusionMalignancyRelated` INT NULL,
CHANGE `TTMTESTIOTMM` `otherMethod` INT NULL,
CHANGE `TMORRESTIOTSI` `otherInvolved`INT NULL,
CHANGE `TMLOCTIOTS` `otherSpecification` VARCHAR(255),
CHANGE `TMORRESUMLD` `baselineSumLongestDiameters` FLOAT;

ALTER TABLE C3_labvalues
CHANGE `LBDTCHAEM` `labHaematologySampleDate` VARCHAR(255),
CHANGE `LBORRESWBC` `WBC` FLOAT,
CHANGE `LBORRESNEU` `neutrophils` FLOAT,
CHANGE `LBORRESPLAT` `platelets` FLOAT,
CHANGE `LBORRESHB` `hemoglobin` FLOAT,
CHANGE `LBDTCBIOCH` `labBiochemistrySampleDate` VARCHAR(255),
CHANGE `LBORRESCRP` `CRP` FLOAT,
CHANGE `LBORRESALKP` `alkalinePhosphatase` FLOAT,
CHANGE `LBORRESBILIV` `totalBilirubin` FLOAT,
CHANGE `LBORRESASAT` `ASAT` FLOAT,
CHANGE `LBORRESALAT` `ALAT` FLOAT,
CHANGE `LBORRESCREA` `creatinin` FLOAT,
CHANGE `LBORRESCREAC` `creatininClearance` FLOAT,
CHANGE `LBORRESNA` `natrium` FLOAT,
CHANGE `LBORRESK` `kalium` FLOAT,
CHANGE `LBORRESCA` `calcium` FLOAT,
CHANGE `LBORRESPHOS` `phosphatase` FLOAT,
CHANGE `LBORRESALB` `albumine` FLOAT,
CHANGE `LBORRESLDH` `ldh` FLOAT,
CHANGE `LBDTCURINA` `labUrinalysisSampleDate` VARCHAR(255),
CHANGE `LBORRESDIPSTICK` `proteinDipstick`INT NULL,
CHANGE `LBORRESPROT` `proteinG24H` FLOAT,

CHANGE `LBORRESPROTGL` `proteinGL` FLOAT,
CHANGE `COLB` `labComments` VARCHAR(255);