package com.hartwig.actin.personalization.database

import com.hartwig.actin.personalization.database.datamodel.ReferenceEntry
import com.hartwig.actin.personalization.datamodel.ReferencePatient
import com.hartwig.actin.personalization.datamodel.Tumor

object ReferenceEntryFactory {

    fun create(patient: ReferencePatient, tumor: Tumor): ReferenceEntry {
        val sortedMetastases = tumor.metastaticDiagnosis.metastases.sortedBy { metastasis -> metastasis.daysSinceDiagnosis }
        val earliestDistantMetastasisDetectionDays = sortedMetastases.firstOrNull()?.daysSinceDiagnosis
//        val systemicTreatmentPostMetastasis =
//            findSystemicTreatmentPostMetastasis(tumor.treatmentEpisodes, earliestDistantMetastasisDetectionDays)

        return ReferenceEntry(
            source = patient.source,
            sourceId = patient.sourceId,
            diagnosisYear = tumor.diagnosisYear,
            ageAtDiagnosis = tumor.ageAtDiagnosis,
            isAlive = tumor.latestSurvivalMeasurement.isAlive,
            sex = patient.sex,
            basisOfDiagnosis = tumor.primaryDiagnosis.basisOfDiagnosis,
            numberOfPriorTumors = tumor.priorTumors.size,
            hasDoublePrimaryTumor = tumor.primaryDiagnosis.hasDoublePrimaryTumor,
            primaryTumorType = tumor.primaryDiagnosis.primaryTumorType,
            primaryTumorLocation = tumor.primaryDiagnosis.primaryTumorLocation,
            sidedness = tumor.primaryDiagnosis.sidedness,
            anorectalVergeDistanceCategory = tumor.primaryDiagnosis.anorectalVergeDistanceCategory,
            mesorectalFasciaIsClear = tumor.primaryDiagnosis.mesorectalFasciaIsClear,
            distanceToMesorectalFasciaMm = tumor.primaryDiagnosis.distanceToMesorectalFasciaMm,
            differentiationGrade = tumor.primaryDiagnosis.differentiationGrade,
            clinicalTnmT = tumor.primaryDiagnosis.clinicalTnmClassification.tnmT,
            clinicalTnmN = tumor.primaryDiagnosis.clinicalTnmClassification.tnmN,
            clinicalTnmM = tumor.primaryDiagnosis.clinicalTnmClassification.tnmM,
            pathologicalTnmT = tumor.primaryDiagnosis.pathologicalTnmClassification.tnmT,
            pathologicalTnmN = tumor.primaryDiagnosis.pathologicalTnmClassification.tnmN,
            pathologicalTnmM = tumor.primaryDiagnosis.pathologicalTnmClassification.tnmM,
            clinicalTumorStage = tumor.primaryDiagnosis.clinicalTumorStage,
            pathologicalTumorStage = tumor.primaryDiagnosis.pathologicalTumorStage,
            investigatedLymphNodesCountPrimaryDiagnosis = tumor.primaryDiagnosis.investigatedLymphNodesCount,
            positiveLymphNodesCountPrimaryDiagnosis = tumor.primaryDiagnosis.positiveLymphNodesCount,
            presentedWithIleus = tumor.primaryDiagnosis.presentedWithIleus,
            presentedWithPerforation = tumor.primaryDiagnosis.presentedWithPerforation,
            venousInvasionDescription = tumor.primaryDiagnosis.venousInvasionDescription,
            lymphaticInvasionCategory = tumor.primaryDiagnosis.lymphaticInvasionCategory,
            extraMuralInvasionCategory = tumor.primaryDiagnosis.extraMuralInvasionCategory,
            tumorRegression = tumor.primaryDiagnosis.tumorRegression,
            isMetachronous = tumor.metastaticDiagnosis.isMetachronous,
            numberOfLiverMetastases = tumor.metastaticDiagnosis.numberOfLiverMetastases,
            maximumSizeOfLiverMetastasisMm = tumor.metastaticDiagnosis.maximumSizeOfLiverMetastasisMm,
            investigatedLymphNodesCountMetastaticDiagnosis = tumor.metastaticDiagnosis.investigatedLymphNodesCount,
            positiveLymphNodesCountMetastaticDiagnosis = tumor.metastaticDiagnosis.positiveLymphNodesCount,
            metastasisLocationGroups = sortedMetastases.joinToString(",") { it.location.name },
            metastasisLocationGroupsDays = sortedMetastases.joinToString(",") { it.daysSinceDiagnosis.toString() },
            earliestDistantMetastasisDetectionDays = earliestDistantMetastasisDetectionDays,
            AllWhoAssessments = "",
            WhoAssessmentsDates = "",
            WhoAssessmentBeforeMetastasisTreatment = 0.0,
            WhoAssessmentDateBeforeMetastasisTreatment = 0.0,
            WhoAssessmentAtMetastasisDetection = 0.0,
            WhoAssessmentDateAtMetastasisDetection = 0.0,
            AllAsaAssessments = "",
            AsaAssessmentsDates = "",
            AsaAssessmentBeforeMetastasisTreatment = "",
            AsaAssessmentDateBeforeMetastasisTreatment = 0.0,
            AsaAssessmentAtMetastasisDetection = "",
            AsaAssessmentDateAtMetastasisDetection = 0.0,
            lactateDehydrogenaseMetastasisDetection = 0.0,
            alkalinePhosphataseMetastasisDetection = 0.0,
            leukocytesAbsoluteMetastasisDetection = 0.0,
            carcinoembryonicAntigenMetastasisDetection = 0.0,
            albumineMetastasisDetection = 0.0,
            neutrophilsAbsoluteMetastasisDetection = 0.0,
            closestLabValueDateMetastasisDetection = 0.0,
            surgeriesPrimary = "",
            surgeriesPrimaryDates = "",
            surgeriesMetastatic = "",
            surgeriesMetastaticDates = "",
            surgeriesGastroenterology = "",
            surgeriesGastroenterologyDates = "",
            hadHipec = 0,
            hadHipecDate = 0.0,
            radiotherapiesPrimary = "",
            radiotherapiesPrimaryDates = "",
            radiotherapiesMetastatic = "",
            radiotherapiesMetastaticDates = "",
            treatment = "",
            firstTreatmentStartAfterMetastasis = 0.0,
            treatmentStop = 0.0,
            numberOfCycles = 0.0,
            hasHadPriorSystemicTherapy = 0,
            hadSurvivalEvent = 0,
            hasHadPriorTumor = 0,
            observedOsFromTumorIncidenceDays = 0,
            observedOsFromMetastasisDetectionDays = 0.0,
            observedOsFromTreatmentStartDays = 0.0,
            systemicTreatmentPlanDuration = 0.0
        )
    }
}