package com.hartwig.actin.personalization.ncr.datamodel

data class DiagnosisEpisode  (
    override val id: Int,
    override val order: Int,
    override val whoStatusPreTreatmentStart: Int?,
    override val asaClassificationPreSurgeryOrEndoscopy: AsaClassificationPreSurgeryOrEndoscopy?,

    override val tumorIncidenceYear: Int,
    override val tumorBasisOfDiagnosis: TumorBasisOfDiagnosis,
    override val tumorLocation: TumorLocation,
    override val tumorDifferentiationGrade: TumorDifferentiationGrade?,
    override val tnmCT: TNM_T?,
    override val tnmCN: TNM_N?,
    override val tnmCM: TNM_M?,
    override val tnmPT: TNM_T?,
    override val tnmPN: TNM_N?,
    override val tnmPM: TNM_M?,
    override val stageCTNM: StageTNM?,
    override val stagePTNM: StageTNM?,
    override val stageTNM: StageTNM?,
    override val numberOfInvestigatedLymphNodes: Int?,
    override val numberOfPositiveLymphNodes: Int?,

    override val distantMetastasesStatus: DistantMetastasesStatus,
    override val metastases: List<Metastases>,
    override val hasKnownLiverMetastases: Boolean,
    override val numberOfLiverMetastases: Int?,
    override val maximumSizeOfLiverMetastasis: Int?,

    val cci: Int?,
    val cciNumberOfCategories: CciNumberOfCategories?,
    val cciHasAids: Boolean?,
    val cciHasCongestiveHeartFailure: Boolean?,
    val cciHasCollagenosis: Boolean?,
    val cciHasCopd: Boolean?,
    val cciHasCerebrovascularDisease: Boolean?,
    val cciHasDementia: Boolean?,
    val cciHasDiabetesMellitus: Boolean?,
    val cciHasDiabetesMellitusWithEndOrganDamage: Boolean?,
    val cciHasOtherMalignancy: Boolean?,
    val cciHasOtherMetastaticSolidTumor: Boolean?,
    val cciHasMyocardialInfarct: Boolean?,
    val cciHasMildLiverDisease: Boolean?,
    val cciHasHemiplegiaOrParaplegia: Boolean?,
    val cciHasPeripheralVascularDisease: Boolean?,
    val cciHasRenalDisease: Boolean?,
    val cciHasLiverDisease: Boolean?,
    val cciHasUlcerDisease: Boolean?,


    ): Episode
