package com.hartwig.actin.personalization.ncr.datamodel

data class FollowupEpisode (
    override val id: Int,
    override val order: Int,
    override val whoStatusPreTreatmentStart: Int?,
    override val asaClassificationPreSurgeryOrEndoscopy: AsaClassificationPreSurgeryOrEndoscopy?,

    override val tumorIncidenceYear: Int,
    override val tumorBasisOfDiagnosis: TumorBasisOfDiagnosis,
    override val tumorLocation: TumorLocation,
    override val tumorDifferentiationGrade: TumorDifferentiationGrade?,
    override val tnmCT: TNM_T?,
    override val tnmCN: TNM_N?,
    override val tnmCM: TNM_M?,
    override val tnmPT: TNM_T?,
    override val tnmPN: TNM_N?,
    override val tnmPM: TNM_M?,
    override val stageCTNM: StageTNM?,
    override val stagePTNM: StageTNM?,
    override val stageTNM: StageTNM?,
    override val numberOfInvestigatedLymphNodes: Int?,
    override val numberOfPositiveLymphNodes: Int?,

    override val distantMetastasesStatus: DistantMetastasesStatus,
    override val metastases: List<Metastasis>,
    override val hasKnownLiverMetastases: Boolean,
    override val numberOfLiverMetastases: Int?,
    override val maximumSizeOfLiverMetastasis: Int?,

    override val hasDoublePrimaryTumor: Boolean?,
    override val mesorectalFasciaIsClear: Boolean?,
    override val distanceToMesorectalFascia: Int?,
    override val venousInvasionCategory: VenousInvasionCategory?,
    override val lymphaticInvasionCategory: LymphaticInvasionCategory?,
    override val extraMuralInvastionCategory: ExtraMuralInvasionCategory?,
    override val tumorRegression: TumorRegression?,

    override val labMeasurements: List<LabMeasurement>,

    override val hasReceivedTumorDirectedTreatment: Boolean,
    override val reasonRefrainmentFromTumorDirectedTreatment : ReasonRefrainmentFromTumorDirectedTreatment?,
    override val hasParticipatedInTrial: Boolean?,

    override val mdlResections: List<MDLResection>,
    override val surgeries: List<Surgery>,
    override val surgeriesMetastases: List<SurgeryMetastases>,
    override val radiotherapies: List<Radiotherapy>,
    override val radiotherapiesMetastases: List<RadiotherapyMetastases>,
    override val hasHadHipecTreatment: Boolean,
    override val intervalTumorIncidenceHipecTreatment: Int?,
    override val systemicTreatments: List<SystemicTreatment>,
    override val treatmentLines: List<SystemicTreatmentScheme>,
    override val hasHadPreSurgeryRadiotherapy: Boolean,
    override val hasHadPostSurgeryRadiotherapy: Boolean,
    override val hasHadPreSurgeryChemoRadiotherapy: Boolean,
    override val hasHadPostSurgeryChemoRadiotherapy: Boolean,
    override val hasHadPreSurgerySystemicChemotherapy: Boolean,
    override val hasHadPostSurgerySystemicChemotherapy: Boolean,
    override val hasHadPreSurgerySystemicTargetedTherapy: Boolean,
    override val hasHadPostSurgerySystemicTargetedTherapy: Boolean,

    override val responseMeasure: ResponseMeasure?,
    override val pfsMeasures: List<PFSMeasure>,

    ): Episode