package com.hartwig.actin.personalization.ncr.datamodel

enum class MDLResectionType {
    ENDOSCOPIC_RESECTION_POLYPECTOMY,
    ENDOMUCOSAL_RESECTION,
    ENDOSUBMUCOSAL_DISSECTION,
    ENDOSCOPIC_FULL_THICKNESS_RESECTION,
    ENDOSCOPIC_INTERMUSCULAR_DISSECTION,
    LOCAL_TUMOR_RESECTION_NOS,
    LOCAL_TUMOR_EXCISION_NOS,
    ABLATION,
    LOCAL_TUMOR_DESTRUCTION,
}