package com.hartwig.actin.personalization.ncr.datamodel

data class NcrLabValues(
    val prechirCea: Double? = null,
    val postchirCea: Double? = null,
    val ldh1: Int? = null,
    val ldh2: Int? = null,
    val ldh3: Int? = null,
    val ldh4: Int? = null,
    val ldhInt1: Int? = null,
    val ldhInt2: Int? = null,
    val ldhInt3: Int? = null,
    val ldhInt4: Int? = null,
    val af1: Int? = null,
    val af2: Int? = null,
    val af3: Int? = null,
    val af4: Int? = null,
    val afInt1: Int? = null,
    val afInt2: Int? = null,
    val afInt3: Int? = null,
    val afInt4: Int? = null,
    val neutro1: Double? = null,
    val neutro2: Double? = null,
    val neutro3: Double? = null,
    val neutro4: Double? = null,
    val neutroInt1: Int? = null,
    val neutroInt2: Int? = null,
    val neutroInt3: Int? = null,
    val neutroInt4: Int? = null,
    val albumine1: Double? = null,
    val albumine2: Double? = null,
    val albumine3: Double? = null,
    // TODO (KD): Pending NCR update = null, albumine4 will become a Double
    val albumine4: Int? = null,
    val albumineInt1: Int? = null,
    val albumineInt2: Int? = null,
    val albumineInt3: Int? = null,
    val albumineInt4: Int? = null,
    val leuko1: Double? = null,
    val leuko2: Double? = null,
    val leuko3: Double? = null,
    val leuko4: Double? = null,
    val leukoInt1: Int? = null,
    val leukoInt2: Int? = null,
    val leukoInt3: Int? = null,
    val leukoInt4: Int? = null
)
