package com.hartwig.actin.personalization.ncr.datamodel

data class NcrMetastaticDiagnosis(
    val metaTopoSublok1: String? = null,
    val metaTopoSublok2: String? = null,
    val metaTopoSublok3: String? = null,
    val metaTopoSublok4: String? = null,
    val metaTopoSublok5: String? = null,
    val metaTopoSublok6: String? = null,
    val metaTopoSublok7: String? = null,
    val metaTopoSublok8: String? = null,
    val metaTopoSublok9: String? = null,
    val metaTopoSublok10: String? = null,
    val metaInt1: Int? = null,
    val metaInt2: Int? = null,
    val metaInt3: Int? = null,
    val metaInt4: Int? = null,
    val metaInt5: Int? = null,
    val metaInt6: Int? = null,
    val metaInt7: Int? = null,
    val metaInt8: Int? = null,
    val metaInt9: Int? = null,
    val metaInt10: Int? = null,
    val metaProg1: Int? = null,
    val metaProg2: Int? = null,
    val metaProg3: Int? = null,
    val metaProg4: Int? = null,
    val metaProg5: Int? = null,
    val metaProg6: Int? = null,
    val metaProg7: Int? = null,
    val metaProg8: Int? = null,
    val metaProg9: Int? = null,
    val metaProg10: Int? = null,
    val metaLeverAantal: Int? = null,
    val metaLeverAfm: Int? = null
)
