package com.hartwig.actin.personalization.ncr.datamodel

data class NcrPriorMalignancies(
    val mal1Int: Int? = null,
    val mal2Int: Int? = null,
    val mal3Int: Int? = null,
    val mal4Int: Int? = null,
    val mal1TopoSublok: String? = null,
    val mal2TopoSublok: String? = null,
    val mal3TopoSublok: String? = null,
    val mal4TopoSublok: String? = null,
    val mal1Morf: Int? = null,
    val mal2Morf: Int? = null,
    val mal3Morf: Int? = null,
    val mal4Morf: Int? = null,
    val mal1Tumsoort: Int? = null,
    val mal2Tumsoort: Int? = null,
    val mal3Tumsoort: Int? = null,
    val mal4Tumsoort: Int? = null,
    val mal1Stadium: String? = null,
    val mal2Stadium: String? = null,
    val mal3Stadium: String? = null,
    val mal4Stadium: String? = null,
    val mal1Syst: Int? = null,
    val mal2Syst: Int? = null,
    val mal3Syst: Int? = null,
    val mal4Syst: Int? = null,
    val mal1SystCode1: String? = null,
    val mal2SystCode1: String? = null,
    val mal3SystCode1: String? = null,
    val mal1SystCode2: String? = null,
    val mal2SystCode2: String? = null,
    val mal3SystCode2: String? = null,
    val mal1SystCode3: String? = null,
    val mal2SystCode3: String? = null,
    val mal3SystCode3: String? = null,
    val mal1SystCode4: String? = null,
    val mal2SystCode4: String? = null,
    val mal3SystCode4: String? = null,
    val mal1SystCode5: String? = null,
    val mal2SystCode5: String? = null,
    val mal1SystCode6: String? = null,
    val mal1SystCode7: String? = null,
    val mal1SystCode8: String? = null,
    val mal1SystCode9: String? = null
)
