package com.hartwig.actin.personalization.ncr.datamodel

enum class SurgeryType {
    APPENDECTOMY,
    HEMICOLECTOMY_OR_ILEOCECAL_RESECTION,
    TRANSVERSUM_RESECTION,
    SIGMOID_RESECTION,
    TRANSANAL_ENDOSCOPIC_MICROSURGERY,
    LOW_ANTERIOR_RESECTION,
    ABDOMINOPERINEAL_RESECTION,
    NOS_OR_OTHER
}