package com.hartwig.actin.personalization.ncr.datamodel

enum class TumorBasisOfDiagnosis {
    CLINICAL_ONLY_INVESTIGATION,
    CLINICAL_AND_DIAGNOSTIC_INVESTIGATION,
    SPEC_BIOCHEMICAL_IMMUNOLOGICAL_LAB_INVESTIGATION,
    CYTOLOGICAL_CONFIRMATION,
    HISTOLOGICAL_CONFIRMATION_METASTASES,
    HISTOLOGICAL_CONFIRMATION
}