#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

database_credentials="$(prod_writer_sql_credentials)"
database_name="actin_personalization"

if [[ -z "${database_credentials}" || -z "${database_name}" ]]; then
    error "Parameters missing. Exiting"
fi

actin_personalization_database_sql="database/src/main/resources/generate_database.sql"
actin_personalization_views_sql="database/src/main/resources/generate_views.sql"

db_host=$(extract_database_host "${database_credentials}")
db_port=$(extract_database_port "${database_credentials}")
db_user=$(extract_database_user "${database_credentials}")
db_pass=$(extract_database_password "${database_credentials}")

info "Rebuilding ACTIN personalization db '${database_name}' on '${db_host}' using ${actin_personalization_database_sql} and ${actin_personalization_views_sql}"

mysql ${database_name} --host="${db_host}" --port="${db_port}" --user="${db_user}" --password="${db_pass}" < ${actin_personalization_database_sql}
mysql ${database_name} --host="${db_host}" --port="${db_port}" --user="${db_user}" --password="${db_pass}" < ${actin_personalization_views_sql}

info "Done!"
