#!/usr/bin/env bash

source message_functions || exit 1
source database_functions || exit 1

ncr_file=$1 && shift

database_credentials="$(prod_writer_sql_credentials)"
database_name="actin_personalization"

if [[ -z "${database_credentials}" || -z "${database_name}" ]]; then
    error "Parameters missing. Exiting"
fi

db_url=$(construct_database_url "${database_credentials}" "${database_name}")
db_user=$(extract_database_user "${database_credentials}")
db_pass=$(extract_database_password "${database_credentials}")

info "Reloading ACTIN personalization db '${database_name}' using ${db_url}"

java -cp "database/target/database-local-SNAPSHOT.jar" com.hartwig.actin.personalization.database.PersonalizationLoaderApplicationKt \
    -ncr_file "${ncr_file}" \
    -db_user "${db_user}" \
    -db_pass "${db_pass}" \
    -db_url "${db_url}" \
    "$@"
