package com.hartwig.actin.personalization.ncr.serialization

data class NCRLabValues(
    val prechirCea: Double?,
    val postchirCea: Double?,
    val ldh1: Int?,
    val ldh2: Int?,
    val ldh3: Int?,
    val ldh4: Int?,
    val ldhInt1: Int?,
    val ldhInt2: Int?,
    val ldhInt3: Int?,
    val ldhInt4: Int?,
    val af1: Int?,
    val af2: Int?,
    val af3: Int?,
    val af4: Int?,
    val afInt1: Int?,
    val afInt2: Int?,
    val afInt3: Int?,
    val afInt4: Int?,
    val neutro1: Double?,
    val neutro2: Double?,
    val neutro3: Double?,
    val neutro4: Double?,
    val neutroInt1: Int?,
    val neutroInt2: Int?,
    val neutroInt3: Int?,
    val neutroInt4: Int?,
    val albumine1: Double?,
    val albumine2: Double?,
    val albumine3: Double?,
    // TODO (KD): Figure out why albumine4 is an integer rather than double!
    val albumine4: Int?,
    val albumineInt1: Int?,
    val albumineInt2: Int?,
    val albumineInt3: Int?,
    val albumineInt4: Int?,
    val leuko1: Double?,
    val leuko2: Double?,
    val leuko3: Double?,
    val leuko4: Double?,
    val leukoInt1: Int?,
    val leukoInt2: Int?,
    val leukoInt3: Int?,
    val leukoInt4: Int?
)
