package com.hartwig.actin.personalization.ncr.serialization

data class NCRMetastases(
    val metaTopoSublok1: String,
    val metaTopoSublok2: String,
    val metaTopoSublok3: String,
    val metaTopoSublok4: String,
    val metaTopoSublok5: String,
    val metaTopoSublok6: String,
    val metaTopoSublok7: String,
    val metaTopoSublok8: String,
    val metaTopoSublok9: String,
    val metaTopoSublok10: String,
    val metaInt1: Int?,
    val metaInt2: Int?,
    val metaInt3: Int?,
    val metaInt4: Int?,
    val metaInt5: Int?,
    val metaInt6: Int?,
    val metaInt7: Int?,
    val metaInt8: Int?,
    val metaInt9: Int?,
    val metaInt10: Int?,
    val metaProg1: Int?,
    val metaProg2: Int?,
    val metaProg3: Int?,
    val metaProg4: Int?,
    val metaProg5: Int?,
    val metaProg6: Int?,
    val metaProg7: Int?,
    val metaProg8: Int?,
    val metaProg9: Int?,
    val metaProg10: Int?,
    val metaLeverAantal: Int?,
    val metaLeverAfm: Int?
)
