package com.hartwig.actin.personalization.datamodel.v2.treatment

enum class SurgeryType {
    ABDOMINOPERINEAL_RESECTION,
    APPENDECTOMY,
    HEMICOLECTOMY_OR_ILEOCECAL_RESECTION,
    LOW_ANTERIOR_RESECTION,
    NOS_OR_OTHER,
    SIGMOID_RESECTION,
    SUBTOTAL_COLECTOMY,
    TOTAL_COLECTOMY,
    TRANSANAL_ENDOSCOPIC_MICROSURGERY,
    TRANSVERSUM_RESECTION,
}