name: Python Tests

on:
  push:
    paths:
      - 'prediction/src/main/python/**'
      - 'prediction/src/test/python/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    paths:
      - 'prediction/src/main/python/**'
      - 'prediction/src/test/python/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r prediction/src/main/python/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest src/test/python --maxfail=1 --disable-warnings -q
